spring:
  application:
    name: CalendarProject

  datasource:
    url: jdbc:mysql://localhost:3306/calendar   # 메모리 DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update         # 테이블 자동 생성/업데이트 (실무는 validate, none)
    show-sql: true             # 실행되는 SQL 로그 보기
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080